"""add calendar notes

Revision ID: 59f4276d483c
Revises: 18bdc17d36b9
Create Date: 2026-07-08 15:44:11.674553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f4276d483c'
down_revision: Union[str, Sequence[str], None] = '18bdc17d36b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('note_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_notes_id'), 'calendar_notes', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_notes_note_date'), 'calendar_notes', ['note_date'], unique=False)
    op.create_index(op.f('ix_calendar_notes_workspace_id'), 'calendar_notes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_notes_workspace_id'), table_name='calendar_notes')
    op.drop_index(op.f('ix_calendar_notes_note_date'), table_name='calendar_notes')
    op.drop_index(op.f('ix_calendar_notes_id'), table_name='calendar_notes')
    op.drop_table('calendar_notes')
    # ### end Alembic commands ###
